version: "3"
services:
  app1:
    build:                                            #Builds container 1 from your ./app Dockerfile
      context: ./app
    container_name: app1
    networks:
      - app-network

  app2:
    build:			                      #Builds container 2 from your ./app Dockerfile
      context: ./app
    container_name: app2
    networks:
      - app-network

  nginx:                                              #Uses official Nginx image
    image: nginx:latest
    container_name: nginx
    ports:                                            #Maps Nginx container port 8080 to your local port 8080
      - "8080:8080"
    volumes:                                          #Mounts custom nginx.conf and .htpasswd into the container
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./htpasswd:/etc/nginx/.htpasswd
    depends_on:                                       #Starts Nginx after the app containers
      - app1
      - app2
    networks:
      - app-network

networks:                                            #All containers are on the same Docker network so they can talk to each other.
  app-network:
    driver: bridge

